server.port: 8070

spring:
  application.name: api-gateway

  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**

        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/payment/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
