server:
  port: 8050
  error.include-message: always

spring:
  application.name: notification

  data.mongodb:
    host: localhost
    port: 27017
    database: notification-db
    authenticationDatabase: admin
    user: seed
    password: seed

  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key