microservices:
  product: PRODUCT

server:
  port: 8090
  error.include-message: always

spring:
  application.name: payment

  datasource:
    url: jdbc:mysql://localhost/payments
    username: root
    password: seed

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: "false"
    open-in-view: false
    hibernate:
      enable_lazy_load_no_trans: true
      jdbc.lob.non_contextual_creation: true
      format_sql: true
      id.new_generator_mappings: false
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  main:
    lazy-initialization: true

  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key


springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
  packagesToScan: com.david.ds.teles.seed.microservices
  pathsToMatch: /**

api:
  common:
    version: 1.0.0.0
    title: payment-microservice
    description: A seed microservice project to help to guide you

    contact:
      name: David Teles
      url: https://www.linkedin.com/in/david-teles/?locale=en_US
      email: david.ds.teles@gmail.com

  rsp:
    ok: everything looks fine
    badRequest: Bad Request, invalid data or parameters
    notFound: Not found