apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: davidteles/product-microservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: LoadBalancer
  selector:
    app: product
  ports:
  - port: 8080
    targetPort: 8080
